# This file is a template, and might need editing before it works on your project.
# use the official gcc image, based on debian
# can use verions as well, like gcc:5.2
# see https://hub.docker.com/_/gcc/
image: gcc

stages:
  - build
  - benchmark

build:
  stage: build
  # instead of calling g++ directly you can also use some build toolkit like make
  # install the necessary build tools when needed
  before_script:
     - apt update && apt -y install wget make autoconf cmake
  script:
    - mkdir build && cd build
    - cmake ..
    - make
  artifacts:
    paths:
      - kalman

# run tests using the binary built before
benchmark:
  stage: benchmark
  script:
    - wget https://enulp.eu/media/files/out.ppm
    - time .kalman out.ppm
